let name = "Nitish Kamboj";  // String
let age = 25;   // Number
let isLoggedIn = true;  // Boolean
let state;  // Undefined
let nullVariable = null;  // Null
let bigIntValue = BigInt(1234567890123456789012345678901234567890);  // BigInt
let symbolValue = Symbol("unique");  // Symbol:this is a unique identifier



let objectValue = { 
    name: "Nitish", 
    age: 25, 
    isLoggedIn: true 
    };  // Object

    

// Example of a class
    class User {
        constructor(name, age) {
            this.name = name;
            this.age = age;
        }
    }