// let score = 33
// console.log(typeof score);
// let valueInNumber = String(score);
// console.log(typeof valueInNumber);
// console.log(valueInNumber); 


// let score = null
// console.log(typeof score);
// let valueInNumber = Number(score);
// console.log(typeof valueInNumber);
// console.log(valueInNumber); 

// let isLoggedIn = "Nitish";
// let BooleanValue = Boolean(isLoggedIn);
// console.log(BooleanValue);

// let isLoggedIn = "";
// let BooleanValue = Boolean(isLoggedIn);
// console.log(BooleanValue);

// let value = 3
// let negValue = -value;
// console.log(negValue % 2);
// console.log(value **4);

// console.log("10" + (5 + 2)); 
// console.log(10 + 5 + "2"); // Number addition followed by string concatenation
// console.log("10" + 5 + 2); // String concatenation 


// let value = 10;
// value ++; // Increment value by 1
// // value += 5; // Equivalent to value = value + 5
// console.log(value); 

/* == is used to check datatype and === is used to check datatype strickly*/
