// let score = 33
// console.log(typeof score);
// let valueInNumber = String(score);
// console.log(typeof valueInNumber);
// console.log(valueInNumber); 


// let score = null
// console.log(typeof score);
// let valueInNumber = Number(score);
// console.log(typeof valueInNumber);
// console.log(valueInNumber); 

// let isLoggedIn = "Nitish";
// let BooleanValue = Boolean(isLoggedIn);
// console.log(BooleanValue);

let isLoggedIn = "";
let BooleanValue = Boolean(isLoggedIn);
console.log(BooleanValue);