//types of declare myArray

const myArray = [1,2,3,4,5];
// console.log(myArray[0]); 
// console.log(myArray[0] + myArray[1]); 
// console.log(typeof myArray[0]); 

// const name = ["Nitish", "Kamboj"];
// const myArray2 = new Array(1, 2, 3, 4);
// console.log(myArray[4]);


// Array methods
// myArray.push(6);// adds an element to the end of the array
// myArray.unshift(0); // adds an element to the beginning of the array
// myArray.pop(); // removes the last element of the array
// myArray.shift(); // removes the first element of the array
// myArray.splice(2, 1); // removes the element at index 2
// myArray.splice(2, 0, 10); // adds an element at index
// console.log(myArray);
// console.log(myArray.includes(10)); // checks if the array includes the element 10
// console.log(myArray.indexOf(10)); // returns the index of the element 10


const newArray = myArray.join(" - "); // joins the array elements into a string
console.log(newArray); // Output: "1 - 2 - 3 - 4

